# Generated by Django 5.2.8 on 2025-12-09 22:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('tipo', models.JSONField(blank=True, default=list, help_text='Lista de ramos de atividade')),
                ('licitacao', models.BooleanField(default=False, help_text='Possui licitação vigente?')),
                ('emendas', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('aviso', '🔴 Aviso Crítico (Bloqueante)'), ('pendencia', '🟡 Pendência / Alerta'), ('update', '🟢 Novidade / Atualização')], default='pendencia', max_length=20)),
                ('alvo', models.CharField(choices=[('todos', 'Todos os Usuários'), ('gestor', 'Apenas Gestores'), ('view', 'Apenas Visitantes'), ('dev', 'Apenas Desenvolvedores')], default='todos', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=10)),
                ('nf', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data', models.DateField(auto_now_add=True)),
                ('data_entrada', models.DateField(default=datetime.date.today)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('tipo_material', models.CharField(blank=True, choices=[('laboratorio', 'Laboratório'), ('medicamentos', 'Medicamentos'), ('insumo', 'Insumo')], help_text='Tipo do material (Laboratório, Medicamentos, Insumo)', max_length=20, null=True)),
                ('destino_entrada', models.CharField(blank=True, choices=[('atencao_primaria', 'Atenção Primária'), ('hospital', 'Hospital')], help_text='Destino inicial (Atenção Primária ou Hospital)', max_length=30, null=True)),
                ('emenda_origem', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='api.empresa')),
            ],
        ),
    ]
