# Generated by Django 5.2.8 on 2025-11-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='emendas',
            field=models.CharField(blank=True, help_text='Emendas parlamentares vinculadas', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='vigencia',
            field=models.CharField(blank=True, help_text='Vigência da licitação (Ex: Até Dez/2025)', max_length=100, null=True),
        ),
    ]
