# Generated by Django 5.2.8 on 2025-12-10 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacao',
        ),
    ]
