# Generated by Django 5.2.8 on 2025-12-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('aviso', '🔴 Aviso Crítico (Bloqueante)'), ('pendencia', '🟡 Pendência / Alerta'), ('update', '🟢 Novidade / Atualização')], default='pendencia', max_length=20)),
                ('alvo', models.CharField(choices=[('todos', 'Todos os Usuários'), ('gestor', 'Apenas Gestores'), ('view', 'Apenas Visitantes'), ('dev', 'Apenas Desenvolvedores')], default='todos', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
