# Generated by Django 5.2.8 on 2025-11-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_empresa_emendas_empresa_vigencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='vigencia',
        ),
        migrations.AddField(
            model_name='empresa',
            name='contratos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de contratos licitatórios'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='emendas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de emendas'),
        ),
    ]
