# Generated by Django 5.2.8 on 2025-11-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_empresa_vigencia_empresa_contratos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='contratos',
        ),
        migrations.AddField(
            model_name='empresa',
            name='licitacao',
            field=models.BooleanField(default=False, help_text='Possui licitação vigente?'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='emendas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
