# Generated by Django 5.2.8 on 2025-11-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_empresa_contratos_empresa_licitacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='tipo',
            field=models.JSONField(blank=True, default=list, help_text='Lista de ramos de atividade'),
        ),
    ]
