# Generated by Django 5.2.8 on 2025-11-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_empresa_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='emenda_origem',
            field=models.CharField(blank=True, help_text='Nome da emenda utilizada no pagamento', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='empenho',
            field=models.CharField(blank=True, help_text='Nota de Empenho', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='processo',
            field=models.CharField(blank=True, help_text='Nº do Processo Licitatório', max_length=100, null=True),
        ),
    ]
