# Generated by Django 5.2.8 on 2025-11-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transacao_emenda_origem_transacao_empenho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='empenho',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='processo',
        ),
        migrations.AddField(
            model_name='transacao',
            name='destino_entrada',
            field=models.CharField(blank=True, choices=[('atencao_primaria', 'Atenção Primária'), ('hospital', 'Hospital')], help_text='Destino inicial (Atenção Primária ou Hospital)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='tipo_material',
            field=models.CharField(blank=True, choices=[('laboratorio', 'Laboratório'), ('medicamentos', 'Medicamentos'), ('insumo', 'Insumo')], help_text='Tipo do material (Laboratório, Medicamentos, Insumo)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='emenda_origem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
