# Generated by Django 5.2.8 on 2025-11-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_transacao_empenho_remove_transacao_processo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
