import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
django.setup()

from django.db import connection

sql_create_table = """
CREATE TABLE IF NOT EXISTS api_notificacao (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    titulo varchar(100) NOT NULL,
    mensagem text NOT NULL,
    tipo varchar(20) NOT NULL,
    alvo varchar(20) NOT NULL,
    ativo boolean NOT NULL,
    criado_em timestamp with time zone NOT NULL
);
"""

print("--- INICIANDO CORREÇÃO DO BANCO NO RENDER ---")

with connection.cursor() as cursor:
    try:
        print("1. Tentando criar tabela 'api_notificacao'...")
        cursor.execute(sql_create_table)
        print(">> SUCESSO: Tabela criada (ou já existia).")
        
        print("2. Verificando integridade...")
        cursor.execute("SELECT count(*) FROM api_notificacao")
        count = cursor.fetchone()[0]
        print(f">> CONEXÃO OK! Existem {count} notificações no banco.")

    except Exception as e:
        print(f"\nERRO CRÍTICO: {e}")

print("---------------------------------------------")